# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
    - container: maven
      image: maven:latest
      
    - container: maven3-jdk8
      image: maven:3-jdk-8


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    container: maven
    steps:
      - script: mvn -v && java version

  - job: Build2
    container: maven3-jdk8
    steps:
      - script: mvn -v && java version
