# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
    - container: maven
      image: maven:latest
      
    - container: sonar-scanner
      image: darkaru/sonarqube-curl:v1


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    container: maven
    steps:
      - script: mvn -v

  - job: sonarScanner
    container: sonar-scanner
    steps:
      - script: sonar-scanner -v
