# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
    - container: maven
      image: maven:latest
      
    - container: Trivy
      image: darkaru/trivy::v1


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    container: maven
    steps:
      - script: mvn -v

  - job: TrivyScan
    container: trivy
    steps:
      - script: trivy -v
